package com.iprwc.webshop;

public enum Permission {
    AUTHENTICATE, RESERVATION_READ, RESERVATION_WRITE, RESERVATION_UPDATE, RESERVATION_DELETE,
    RESERVATION_WRITE_OTHER, RESERVATION_DELETE_OTHER, RESERVATION_UPDATE_OTHER, ADMIN, NONE, ILLEGAL
}
